bids_dir: /project/6007967/akhanf/cfmm-bids/data/Khan/SNSX_7T_fresh/correct7T.v0.3/gradcorrect_v0.0.3
target_nii: 'sub-{subject}/anat/sub-{subject}_acq-MP2RAGE_run-01_T1w.nii.gz' 

participants_tsv: 'config/participants.tsv'

init_template: 'resources/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz'

max_iters: 4

ants:
    base_opts: '-d 3 --float 1 --verbose 1'
    intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
    shrink_factors: '12x6x4x2x1'  #-f 6x4x2x1 
    smoothing_factors: '6x3x2x1x0vox' # -s 3x2x1x0 
    reg_iterations: '100x100x70x50x10' # -q 100x100x70x20 
    transform_model: 'SyN[0.1,3,0]'
    sim_metric: CC
