in_images:
  T1w: '/project/6007967/akhanf/projects/hcp/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T1w_acpc_dc_restore_brain.nii.gz'
  T2w: '/project/6007967/akhanf/projects/hcp/HCP_1200_T1w_Diffusion_FS/{subject}/T1w/T2w_acpc_dc_restore_brain.nii.gz'

participants_tsv: 'config/participants.tsv'

init_template:
  T1w: '~/.cache/templateflow/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T1w.nii.gz'
  T2w: '~/.cache/templateflow/tpl-MNI152NLin2009cAsym_res-01_desc-brain_T2w.nii.gz'

max_iters: 4

resample_init_template: True #set this True to resample init template to below dims
resample_vox_dims: 
  - 0.7
  - 0.7
  - 0.7


#should be at least 2.3.1 (includes --random-seed option)
ants_container:  '/project/6007967/akhanf/singularity/ants-v2.3.1.sif'

ants:
  dim: 3
  random_seed: 42
  intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
  linear:
    reg_iterations: '1000x500x250x0'
    shrink_factors: '6x4x2x1'
    smoothing_factors: '4x2x1x0'
  deform:
    shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1 
    smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0 
    reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20 
    transform_model: 'SyN[0.1,3,0]'
    sim_metric: CC
  shape_update:
    gradient_step: 0.25
