in_images:
  T1w: '/project/6007967/akhanf/cfmm-bids/data/Khan/SNSX_7T/deriv/gradcorrect_0.0.1h/sub-{subject}/anat/sub-{subject}_acq-MP2RAGE_run-01_T1w.nii.gz'
  T2w: '/project/6007967/akhanf/cfmm-bids/data/Khan/SNSX_7T/deriv/prepT2space_v0.0.1f/sub-{subject}/anat/sub-{subject}_acq-SPACE_proc-prepT2_space-T1w_T2w.nii.gz'

participants_tsv: 'config/participants.tsv'


#assumes that templateflow templates have been grabbed.. 
init_template:
  T1w: '~/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz'
  T2w: '~/.cache/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_T2w.nii.gz'

max_iters: 4



resample_init_template: True #set this True to resample init template to below dims 
# WARNING - changing this can significantly alter memory usage and run-time -- 
resample_vox_dims: 
 - 0.7
 - 0.7
 - 0.7



#should be at least 2.3.4 (includes --random-seed option, and fixes some argparsing bugs)
ants_container:  '/project/6050199/akhanf/singularity/kaczmarj_ants_2.3.4.sif'

ants:
  dim: 3
  random_seed: 42
  intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
  linear:
      reg_iterations: '1000x500x250x0'
      shrink_factors: '6x4x2x1'
      smoothing_factors: '4x2x1x0'
  deform:
      shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1
      smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0
      reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20
      transform_model: 'SyN[0.1,3,0]'
      sim_metric: CC
  shape_update:
      gradient_step: 0.25

#set this to enable quick and dirty ants parameters
enable_quick_dirty: False

#for testing, runs in less than a minute 
ants_quick_dirty:
  dim: 3
  random_seed: 42
  intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
  linear:
    reg_iterations: '1000'
    shrink_factors: '6'
    smoothing_factors: '4'
  deform:
    shrink_factors: '12'  # default in antsMVTC2: 6x4x2x1 
    smoothing_factors: '6vox' # default in antsMVTC2: 3x2x1x0 
    reg_iterations: '50' # default in antsMVTC2: 100x100x70x20 
    transform_model: 'SyN[0.1,3,0]'
    sim_metric: CC
  shape_update:
    gradient_step: 0.25



#for templateflow-style output
template_name: 'mytemplate'  #tpl-{template_name} 

resolution_index: 1 # res-{resolution_index}
#shape, zooms, origin will be obtained from the nifti itself


#for creating the template_description.json file
template_description_extras:
  Name: 'Brief template description goes here'
  Authors:
    - 'Your Name Here'
  Acknowledgements: 'Created by ants_build_template_smk Snakemake workflow'
  BIDSVersion:
    - '1.1.0' 
  License: 'See LICENSE file'
  TemplateFlowVersion: '1.0.0'

